export const GREETING_AUDIOS = {
  morning: [ // 07:30 a 12:00 
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/10_jvsbhs.mp3', 
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/11_ddtxzh.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/12_kv7dc7.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/13_a8blfe.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/14_ke8hml.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/15_pbsmec.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/16_d8ranc.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/17_qf3zmo.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/18_uw1dpy.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/19_gpjhoz.mp3',
  ],
  afternoon: [ // 12:01 a 18:00 
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/20_wn0weh.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/21_fwpqni.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/22_l5bkbz.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/23_ahmio9.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/24_sdjmui.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/25_piazi2.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/26_hpvyxo.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/27_guvt3f.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/28_mcuvlw.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/29_juasvn.mp3',
  ],
  night: [ // 18:01 a 22:00 
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/30_rpschd.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/31_qybjne.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/33_j0xym3.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/34_cu8l1q.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/35_fmvioz.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/36_voxsro.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/37_rnefti.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/38_obcrwl.mp3',
    'https://res.cloudinary.com/dgb6icyzx/video/upload/q_auto:good/39_khytco.mp3',
  ],
};
